
services:
  backend:
    build: .
    image: jackapp-status:1.0.0
    container_name: jackapp
    environment:
      NODE_ENV: "local"
      SERVER_PORT: "3000"
      DATABASE_HOST: "jackapp_database"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "jackapp_database_schema"
      DATABASE_USER: "jackapp_database_username"
      DATABASE_PASS: "jackapp_database_password"
    ports:
      - "3000:3000"
    links:
      - jackapp_database

    depends_on:
        jackapp_database:
            condition: service_healthy
  jackapp_database:
    image: mysql:9.0.1
    container_name: jackapp_database
    restart: always
    command: --bind-address=0.0.0.0
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - jackapp_database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'jackapp_database_schema'
      MYSQL_USER: 'jackapp_database_username'
      MYSQL_PASSWORD: 'jackapp_database_password'
      MYSQL_ROOT_PASSWORD: 'jackapp_database_password_10'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pjackapp_database_password_10"] 
      timeout: 5s
      retries: 3
volumes:
  jackapp_database:
