name: Application CD - Kubernetes Deployment in AWS EKS

on: 
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      aws_session_token:
        description: 'AWS Session Token'
        required: true
      aws_account_id:
        description: 'AWS Account ID'
        required: true
      aws_backend_bucket:
        description: 'AWS S3 Bucket Terraform State'
        required: true
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

jobs:
  terraform:
    name: Application Deployment
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
  
    steps:
      
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Mascarar Credenciais
      run: |
        echo "::add-mask::${{ github.event.inputs.aws_access_key_id }}"
        echo "::add-mask::${{ github.event.inputs.aws_secret_access_key }}"
        echo "::add-mask::${{ github.event.inputs.aws_session_token }}"
        echo "::add-mask::${{ github.event.inputs.aws_account_id }}"
        echo "::add-mask::${{ github.event.inputs.aws_backend_bucket }}"
        echo "::add-mask::${{ github.event.inputs.aws_region }}"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS CLI 
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
        aws-session-token: ${{ github.event.inputs.aws_session_token }}
        aws-region: ${{ github.event.inputs.aws_region }}
            
    - name: Verify AWS CLI Configuration
      run: aws sts get-caller-identity

    - name: Validate AWS Credentials
      run: |
        aws sts get-caller-identity || exit 1

    - name: Download terraform_infrastructure.json from S3 infrastructure jackapp-infra/terraform.tfstate
      run: | 
        aws s3 cp s3://${{ github.event.inputs.aws_backend_bucket }}/jackapp-infra/terraform.tfstate terraform_infrastructure.json 
        
    - name: Extract EKS Cluster Name 
      id: extract-cluster-name
      run: | 
        CLUSTER_NAME=$(jq -r '.outputs.jackapp_cluster_name.value' terraform_infrastructure.json)
        echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_OUTPUT

    - name: Extract SNS Topic ARN for Processing
      id: sns-processing-topic-arn
      run: | 
        SNS_TOPIC_ARN=$(jq -r '.outputs["sns-canal-de-processamento-arn"].value' terraform_infrastructure.json)
        echo "SNS_TOPIC_ARN=$SNS_TOPIC_ARN" >> $GITHUB_OUTPUT       

    - name: Update kubeconfig 
      run: | 
        aws eks update-kubeconfig --name ${{ steps.extract-cluster-name.outputs.CLUSTER_NAME }} --region ${{ github.event.inputs.aws_region }} 
    
    - name: Create file jackapp-status-configmap.yaml
      working-directory: manifesto_kubernetes/
      run: |
          cat <<EOF > jackapp-status-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: jackapp-status-configmap
          data:
            NODE_ENV: production
            DATABASE_HOST: "svc-jackapp-status-database"
            DATABASE_PORT: "${{ secrets.MYSQL_PORT}}"
            DATABASE_NAME: "${{ secrets.MYSQL_DATABASE }}-CLIENTE"
            DATABASE_USER: "${{ secrets.MYSQL_USER }}"
            DATABASE_PASS: "${{ secrets.MYSQL_PASSWORD }}"
            AWS_ACCOUNT_ID: "${{ github.event.inputs.aws_account_id }}"
            AWS_REGION: "${{ github.event.inputs.aws_region }}"
            AWS_ACCESS_KEY_ID: "${{ github.event.inputs.aws_access_key_id }}"
            AWS_SECRET_ACCESS_KEY: "${{ github.event.inputs.aws_secret_access_key }}"
            AWS_SESSION_TOKEN: "${{ github.event.inputs.aws_session_token }}"
            SNS_TOPIC_ARN: "${{ steps.sns-processing-topic-arn.outputs.SNS_TOPIC_ARN }}"
            SNS_BASE_URL: "https://sns.${{ github.event.inputs.aws_region }}.amazonaws.com"
          EOF

    - name: Create file jackapp-status-database-configmap.yaml
      working-directory: manifesto_kubernetes/
      run: |
        cat <<EOF > jackapp-status-database-configmap.yaml
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: jackapp-status-database-configmap
        data:
          MYSQL_DATABASE: "${{ secrets.MYSQL_DATABASE }}-CLIENTE"
          MYSQL_USER: "${{ secrets.MYSQL_USER }}"
          MYSQL_PASSWORD: "${{ secrets.MYSQL_PASSWORD }}"
          MYSQL_ROOT_PASSWORD: "${{ secrets.MYSQL_ROOT_PASSWORD }}"
        EOF

    - name: Deploy in AWS EKS Cluster
      working-directory: manifesto_kubernetes/ 
      run: |
        kubectl apply -f jackapp-status-database-configmap.yaml
        kubectl apply -f jackapp-status-configmap.yaml
        kubectl apply -f svc-jackapp-status.yaml
        kubectl apply -f svc-jackapp-status-database.yaml
        kubectl apply -f pv-jackapp-status-database.yaml
        kubectl apply -f pvc-jackapp-status-database.yaml
        kubectl apply -f jackapp-status-hpa.yaml
        kubectl apply -f jackapp-status-database-deployment.yaml
        kubectl apply -f jackapp-status-deployment.yaml
  
    - name: Obtain Load Balancer Hostname
      id: get-load-balancer-hostname
      run: |
        HOSTNAME=$(kubectl get svc svc-jackapp-status -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        echo "LB_HOSTNAME=$HOSTNAME" >> $GITHUB_OUTPUT
    
    - name: Obter Porta do Load Balancer
      id: get-load-balancer-port
      run: |
        PORT=$(kubectl get svc svc-jackapp-status -o jsonpath='{.spec.ports[0].port}')
        echo "LB_PORT=$PORT" >> $GITHUB_OUTPUT
    
    - name: Export Load Balancer Hostname and Port to S3
      run: |
        echo '{' > jackapp-status.json
        echo '  "lb_hostname": "${{ steps.get-load-balancer-hostname.outputs.LB_HOSTNAME }}",' >> jackapp-status.json
        echo '  "lb_port": "${{ steps.get-load-balancer-port.outputs.LB_PORT }}"' >> jackapp-status.json
        echo '}' >> jackapp-status.json
        aws s3 cp jackapp-status.json s3://${{ github.event.inputs.aws_backend_bucket }}/jackapp-status/jackapp-status.json
